version: '3'
services:
  db:
    build: ./db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker

  api:
    build:
      context: ./api
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./api:/project
    ports:
      - "5000:8080"
    links:
      - db

  app:
    build:
      context: ./app
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./app/src:/app/src 
    ports:
      - "3000:3000"

volumes:
  pgdata: